# Generated by Django 2.2 on 2022-06-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220613_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cv',
            new_name='resumes',
        ),
    ]
