# Generated by Django 2.2 on 2022-06-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220614_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resumes',
        ),
    ]
