# Generated by Django 2.2 on 2022-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contact',
            field=models.CharField(default='XXX XXX XXXX', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resumes',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
