# Generated by Django 2.2 on 2022-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_auto_20220613_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resumes',
            field=models.ImageField(default='static/img/johnny.jpg', upload_to='img'),
        ),
    ]
