# Generated by Django 2.2 on 2022-06-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0004_auto_20220613_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resumes',
        ),
    ]
